## Week 8 - Linear Algebra and Matrix Decomposition

In [121]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    for i in range(n):
        for k in range(i, n):
            sum_upper = sum(L[i][j] * U[j][k] for j in range(i))
            U[i][k] = A[i][k] - sum_upper
        L[i][i] = 1
        for k in range(i + 1, n):
            sum_lower = sum(L[k][j] * U[j][i] for j in range(i))
            L[k][i] = (A[k][i] - sum_lower) / U[i][i]
    return L, U

def forward_substitution(L, b):
    n = len(L)
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - sum(L[i][j] * y[j] for j in range(i))
    return y

def backward_substitution(U, y):
    n = len(U)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(U[i][j] * x[j] for j in range(i + 1, n))) / U[i][i]
    return x

A = np.array([[2, -1, -2], [-4, 6, 3], [-4, -2, 8]], dtype=float)
b = np.array([-2, 9, -5], dtype=float)

L, U = lu_decomposition(A)
y = forward_substitution(L, b)
x = backward_substitution(U, y)

print("L:\n", L)
print("U:\n", U)
print("x:", x)

L:
 [[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]]
U:
 [[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  3.]]
x: [-1.875       0.91666667 -1.33333333]


In [122]:
def qr_decomposition(A):
    n = A.shape[0]
    Q = np.zeros((n, n))
    R = np.zeros((n, n))
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    return Q, R

def solve_qr(Q, R, b):
    y = np.dot(Q.T, b)
    n = R.shape[0]
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(R[i, j] * x[j] for j in range(i + 1, n))) / R[i, i]
    return x

A2 = np.array([[1, 1, 0], [1, 0, 1], [0, 1, 1]], dtype=float)
b2 = np.array([4, 5, 6], dtype=float)

Q, R = qr_decomposition(A2)
x2 = solve_qr(Q, R, b2)

print("Q:\n", Q)
print("R:\n", R)
print("Solution x:", x2)

Q:
 [[ 0.70710678  0.40824829 -0.57735027]
 [ 0.70710678 -0.40824829  0.57735027]
 [ 0.          0.81649658  0.57735027]]
R:
 [[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]
Solution x: [1.5 2.5 3.5]
